services:
  postgres:
    image: postgres:16-alpine3.21
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cromxt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  adminer:
    image: adminer
    ports:
      - 8081:8080